# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 18:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('hazardID', models.AutoField(primary_key=True, serialize=False)),
                ('lower', models.FloatField()),
                ('upper', models.FloatField()),
                ('pga', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Kriva',
            fields=[
                ('vID', models.AutoField(primary_key=True, serialize=False)),
                ('a1', models.FloatField()),
                ('p1', models.FloatField()),
                ('h1', models.FloatField()),
                ('a2', models.FloatField()),
                ('p2', models.FloatField()),
                ('h2', models.FloatField()),
                ('a3', models.FloatField()),
                ('p3', models.FloatField()),
                ('h3', models.FloatField()),
                ('a4', models.FloatField()),
                ('p4', models.FloatField()),
                ('h4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zgrade',
            fields=[
                ('zgradeID', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('brstanara', models.IntegerField(blank=True, default=None, null=True)),
                ('krivapovr', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('krivljudi', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ostecenje', models.FloatField(blank=True, default=None, null=True)),
                ('ljudi', models.FloatField(blank=True, default=None, null=True)),
                ('pga', models.FloatField(blank=True, default=None, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
    ]
