# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 18:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrisk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zgrada',
            fields=[
                ('zgradeID', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('brstanara', models.IntegerField(blank=True, default=None, null=True)),
                ('krivapovr', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('krivljudi', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ostecenje', models.FloatField(blank=True, default=None, null=True)),
                ('ljudi', models.FloatField(blank=True, default=None, null=True)),
                ('pga', models.FloatField(blank=True, default=None, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Zgrade',
        ),
    ]
