# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrisk', '0002_auto_20160909_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgrada',
            name='zgradeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
