# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zrisk', '0005_auto_20160912_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idKorisnika', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('grad', models.CharField(max_length=100)),
                ('opstina', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
            ],
        ),
    ]
